# Generated by Django 4.1.5 on 2023-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_active',
            field=models.BooleanField(default=False, verbose_name='Girişli Profil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='0000', max_length=50, verbose_name='Profil Şifre'),
        ),
    ]
