# Generated by Django 4.1.5 on 2023-05-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_profile_login_active_alter_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
