# Generated by Django 4.1.5 on 2023-05-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0005_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appUser.userinfo', verbose_name='Kullanıcı Bilgiler'),
        ),
    ]
